site_name: Pythonä¸äººå·¥æ™ºèƒ½ è¯¾ç¨‹èµ„æºå¹³å°
site_url: https://mydomain.org/mysite
repo_name: Guyitaoo/ZJUT-Python-AI-website
repo_url: https://github.com/Guyitaoo/notebook.git
theme:
  name: material
  language: zh
  logo: _assets/logo.png
  favicon: _assets/favicon.png
  repo_icon: true
  repo_name: "å®Œæ•´çš„é•¿ä»“åº“åç§°æ˜¾ç¤º"
  icon:
    #repo: fontawesome/brands/git-alt
  features:
    - navigation.tabs
    - content.code.copy
  custom_dir: overrides
plugins:
  - search
  # - glightbox
markdown_extensions:
  - admonition
  - pymdownx.details  # æ”¯æŒå¯æŠ˜å æç¤ºæ¡†
  - pymdownx.superfences  # ä»£ç å—åµŒå¥—
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: "__span"
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
extra_css:
  - _styles/extra.css
  - _styles/components/gallery.css
extra_javascript:
  - _js/components/gallery.js

nav:
  - é¦–é¡µ: index.md
  - è¯¾ç¨‹ç¬”è®°:
      - æ•°å­¦: 
        - é«˜ç­‰æ•°å­¦: math/calculus.md
        - çº¿æ€§ä»£æ•°: math/linear_algebra.md
      - è‹±è¯­: english.md
      - Pythonä¸äººå·¥æ™ºèƒ½:
        - é¦–é¡µ: ai/index.md
        - PythonåŸºç¡€: ai/neural_network.md
      - "Anacondaç¯å¢ƒé…ç½®": 
        - Anacondaç¯å¢ƒé…ç½®(å‘½ä»¤è¡Œ): start_guide/anaconda/anaconda_env.md
        - Anacondaç¯å¢ƒé…ç½®(å›¾å½¢ç•Œé¢): start_guide/anaconda/anaconda_env_gui.md
      - Jupyter Notebookæ•™ç¨‹: start_guide/jupyter_notebook/jupyter_notebook.md
      - ä½œä¸šæäº¤åŠæ³•: start_guide/homework_submission.md
  - æŠ€æœ¯ç§¯ç´¯:
      - é¦–é¡µ: textbook/index.md
      - "Pythonç¨‹åºè®¾è®¡åŸºç¡€æ•™ç¨‹":
          - æ‰‰é¡µ: textbook/python/index.md
          - ç¬¬ä¸€ç«  æ¦‚è¿°: 
            #- textbook/python/chapter1.md
            - "1.4": textbook/python/chapter1/1.4.md
          - ç¬¬äºŒç«  å˜é‡å’Œç®€å•æ•°æ®ç±»å‹: textbook/python/chapter2.md
          - ç¬¬ä¸‰ç«  ç¨‹åºæµç¨‹æ§åˆ¶: textbook/python/chapter3.md
          - ç¬¬å››ç«  åˆ—è¡¨ä¸å…ƒç»„: textbook/python/chapter4.md
          - ç¬¬äº”ç«  å­—å…¸ä¸é›†åˆ: textbook/python/chapter5.md
          - ç¬¬å…­ç«  å‡½æ•°: textbook/python/chapter6.md
          - ç¬¬ä¸ƒç«  æ–‡ä»¶: textbook/python/chapter7.md
          - ç¬¬å…«ç«  é¢å‘å¯¹è±¡ç¨‹åºè®¾è®¡: textbook/python/chapter8.md
      - "äººå·¥æ™ºèƒ½æ•™æ":
          - æ‰‰é¡µ: textbook/ai/index.md
  - ğŸ“šå…¶ä»–å†…å®¹:
      - é¦–é¡µ: courseware/index.md
      - è¯¾ç¨‹PPT: courseware/ppt/index.md
      - è¯¾ç¨‹ä»£ç : courseware/code/index.md
  - ğŸ“Œå…³äº: 
        - å…³äº: about/about.md
        - è´¡çŒ®è€…åå•: about/contributors.md
        - å¹³å°å»ºè®¾å›¢é˜Ÿ: about/team.md